[phases.setup]
# GANTI 'libmagic' MENJADI 'file'
nixPkgs = ["python311", "poppler_utils", "tesseract", "file"]

[phases.install]
cmds = ["python -m venv .venv && . .venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = ". .venv/bin/activate && uvicorn app.main:app --host 0.0.0.0 --port $PORT"